name: Release

on:
  pull_request:
    types: [opened, reopened, labeled]
jobs:
  Patch:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.labels == 'patch' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Version Get
        run: echo "NPM_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${GITHUB_HEAD_REF}
      - name: Version Get
        run: echo "NPM_NEW_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Update Version
        if: ${{ env.NPM_VERSION != env.NPM_NEW_VERSION }}
        run: npm version patch
      - name: Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: git push -u origin ${GITHUB_HEAD_REF}
  Minor:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.labels == 'minor' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Version Get
        run: echo "NPM_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${GITHUB_HEAD_REF}
      - name: Version Get
        run: echo "NPM_NEW_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Update Version
        if: ${{ env.NPM_VERSION != env.NPM_NEW_VERSION }}
        run: npm version minor
      - name: Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: git push -u origin ${GITHUB_HEAD_REF}
  Major:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.labels == 'major' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Version Get
        run: echo "NPM_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${GITHUB_HEAD_REF}
      - name: Version Get
        run: echo "NPM_NEW_VERSION=$(node -e \"console.log(require('./package.json').version)\")" >> $GITHUB_ENV
      - name: Update Version
        if: ${{ env.NPM_VERSION != env.NPM_NEW_VERSION }}
        run: npm version major
      - name: Push
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: git push -u origin ${GITHUB_HEAD_REF}
